version: '3'

networks:
  java-network:
    external: true

services:
  zookeeper-java:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./containers/java/zookeeper/data:/data
      - ./containers/java/zookeeper/datalog:/datalog
    networks:
      - java-network

  kafka1-java:
    image: wurstmeister/kafka
    hostname: kafka1-java
    depends_on:
      - zookeeper-java
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_CLEANER_ENABLE: "true"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zookeeper-java:2181
    volumes:
      - ./containers/java/kafka1/data:/var/lib/kafka/data
    networks:
      - java-network

  kafka2-java:
    image: wurstmeister/kafka
    hostname: kafka2-java
    depends_on:
      - zookeeper-java
    ports:
      - "9093:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 2
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_LOG_CLEANER_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zookeeper-java:2181
    volumes:
      - ./containers/java/kafka2/data:/var/lib/kafka/data
    networks:
      - java-network

  kafka3-java:
    image: wurstmeister/kafka
    hostname: kafka3-java
    depends_on:
      - zookeeper-java
      - kafka1-java
      - kafka2-java
    ports:
      - "9094:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 3
      KAFKA_LOG_CLEANER_ENABLE: "true"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zookeeper-java:2181
    volumes:
      - ./containers/java/kafka3/data:/var/lib/kafka/data
    networks:
      - java-network

  remora-java:
    image: registry.opensource.zalan.do/machina/remora
    depends_on:
      - kafka1-java
      - kafka2-java
      - kafka3-java
    environment:
      KAFKA_ENDPOINT: "kafka1-java:9092, kafka2-java:9093, kafka3-java:9094"
    ports:
      - 9001:9000
    networks:
      - java-network

  kafka-rest-proxy-java:
    image: confluentinc/cp-kafka-rest:5.1.2
    hostname: kafka-rest-proxy-java
    ports:
      - "8002:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper-java:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1-java:9092
    depends_on:
      - zookeeper-java
      - kafka1-java
    networks:
      - java-network

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    hostname: kafka-topics-ui
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy-java:8082/"
      PROXY: "true"
      CADDY_OPTIONS: "basicauth / test test"
    depends_on:
      - zookeeper-java
      - kafka1-java
      - kafka-rest-proxy-java
    networks:
      - java-network