version: '3'

networks:
  java-network:
    external: true

services:
  zookeeper-java:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./containers/java/zookeeper/data:/data
      - ./containers/java/zookeeper/datalog:/datalog
    networks:
      - java-network

  kafka1-java:
    image: wurstmeister/kafka
    hostname: kafka1-java
    depends_on:
      - zookeeper-java
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_CLEANER_ENABLE: "true"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zookeeper-java:2181
    volumes:
      - ./containers/java/kafka1/data:/var/lib/kafka/data
    networks:
      - java-network