version: '2'

networks:
    java-network:
      external: true

services:
  standalone:
    image: apachepulsar/pulsar:2.5.2
    expose:
      - 8080
      - 6650 
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports: 
      - "8080:8080"
      - "6650:6650"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
  dashboard:
    image: apachepulsar/pulsar-dashboard:2.5.2
    depends_on:
      - standalone
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://standalone:8080
