version: '2'
services:
  #Service for nameserver
  activemq-artermis:
    image: vromero/activemq-artemis
    container_name: artemis
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8161:8161
      - 61616:61616
    environment: 
        ARTEMIS_USERNAME: mq-test
        ARTEMIS_PASSWORD: mq-test